In [1]:
#code to verify numpy array takes lesser memory than python lists
import numpy as np
import time
import sys
python_list= list(range(1000))
print("For list of string : ",sys.getsizeof("s")*len(python_list))
print("For list of integers : ",sys.getsizeof(5)*len(python_list))
#print(sys.getsizeof(0)*len(python_list))
numpy_array= np.arange(1000)
print("For numpy array of integers : ",numpy_array.size*numpy_array.itemsize)

For list of string :  50000
For list of integers :  28000
For numpy array of integers :  4000


In [2]:
#code to verify numpy arrays are faster than python lists
import time
import sys
 
SIZE = 1000000
 
list_one= range(SIZE)
list_two= range(SIZE)
array_one= np.arange(SIZE)
array_two= np.arange(SIZE)
 
start= time.time()
result=[(x,y) for x,y in zip(list_one,list_two)]
print("Time to process lists : ",(time.time()-start)*1000)
 
start=time.time()
result= array_one+array_two
print("Time to process array : ",(time.time()-start)*1000)

Time to process lists :  623.6133575439453
Time to process array :  331.80761337280273


In [3]:
# creating array using list of lists
# we use np.array function to create new array
new_list=[[1,2,3],[4,5,6]]
new_array=np.array(new_list)
print("Our array 2D is : ")
print(new_array)

Our array 2D is : 
[[1 2 3]
 [4 5 6]]


In [4]:
# checking attributes of array
print("Dimensions: ",new_array.ndim)
print("Shape: ",new_array.shape)
print("Size: ",new_array.size)#number of elements in an array
print("Data Type: ",new_array.dtype)
print("Item size: ",new_array.itemsize)

Dimensions:  2
Shape:  (2, 3)
Size:  6
Data Type:  int32
Item size:  4


In [5]:
new_array.data#buffer

In [6]:
# we can reshape original array to new size using reshape method
# original array does not change
print("original array is : ")
print(new_array)
#new_array.reshape(1,6)
print("Our modified array is : ")
print(new_array.reshape(3,2))
print("Our modified array is : ")
print(new_array.reshape(1,6))
print("Our modified array is : ")
print(new_array.reshape(6,1))

original array is : 
[[1 2 3]
 [4 5 6]]
Our modified array is : 
[[1 2]
 [3 4]
 [5 6]]
Our modified array is : 
[[1 2 3 4 5 6]]
Our modified array is : 
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [7]:
# creating new array using arange function
new_array=np.arange(6).reshape(2,3)

In [8]:
# we can specify data type of the data in array
np.array(new_array,dtype=float)

array([[0., 1., 2.],
       [3., 4., 5.]])

In [9]:
# we can create array ,initialised with zeros
zeros_array=np.zeros((2,3),dtype=float)
print("Zeros array is : ")
print(zeros_array)

Zeros array is : 
[[0. 0. 0.]
 [0. 0. 0.]]


In [10]:
# we can create array , initialised with ones
ones_array=np.ones((2,3),dtype=float)
print("Ones array is : ")
print(ones_array)

Ones array is : 
[[1. 1. 1.]
 [1. 1. 1.]]


In [11]:
# we can create empty array ,which will get initialised to random numbers
empty_array=np.empty((2,3),dtype=int)
print("Empty array is : ")
print(empty_array)

Empty array is : 
[[ 75825266         0         0]
 [        0         1 538976288]]


In [12]:
row_array=np.arange(10,30,5)
row_array

array([10, 15, 20, 25])

In [13]:
row_array=np.arange(0,2,0.3)
print(row_array)
type(row_array)

[0.  0.3 0.6 0.9 1.2 1.5 1.8]


numpy.ndarray

In [14]:
new_array=np.linspace(0,2,9)
print(new_array)

[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]


In [15]:
raw_array=np.arange(10000).reshape(100,100)
print("Our array is : ")
print(raw_array)

Our array is : 
[[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [9700 9701 9702 ... 9797 9798 9799]
 [9800 9801 9802 ... 9897 9898 9899]
 [9900 9901 9902 ... 9997 9998 9999]]


In [16]:
# addition of two array elements
one_array=np.array([0,1,2,3,4])
two_array=np.array([5,6,7,8,9])
print("Our first array is : ",one_array)
print("Our second array is : ",two_array)
summation=one_array+two_array
print("Addtion of above two arrays is : ")
print(summation)

Our first array is :  [0 1 2 3 4]
Our second array is :  [5 6 7 8 9]
Addtion of above two arrays is : 
[ 5  7  9 11 13]


In [17]:
print("Our first array is : ",one_array)
print("Our second array is : ",two_array)
subtraction=one_array-two_array
print("Subtraction of above two arrays is : ")
print(subtraction)

Our first array is :  [0 1 2 3 4]
Our second array is :  [5 6 7 8 9]
Subtraction of above two arrays is : 
[-5 -5 -5 -5 -5]


In [18]:
# multiply each element of array with constant
print("Our original array is : ",one_array)
# original array does not change
print("After multiplication with 2, we got : ",one_array*2)

Our original array is :  [0 1 2 3 4]
After multiplication with 2, we got :  [0 2 4 6 8]


In [19]:
# use of conditional operator 
print("Our original array is : ",one_array)
print("After application of conditional operator on above array, we got : ",one_array<3)

Our original array is :  [0 1 2 3 4]
After application of conditional operator on above array, we got :  [ True  True  True False False]


In [20]:
# use of conditional operator 
print("Our original array is : ",one_array)
print("After application of conditional operator on above array, we got : ",one_array[one_array<3])

Our original array is :  [0 1 2 3 4]
After application of conditional operator on above array, we got :  [0 1 2]


In [21]:
# getting maximum element from the array
print("Our original array is : ",one_array)
print("Maximum element from the above array is : ",one_array.max())

Our original array is :  [0 1 2 3 4]
Maximum element from the above array is :  4


In [22]:
# getting minimum element from the array
print("Our original array is : ",one_array)
print("Minimum element from the above array is : ",one_array.min())

Our original array is :  [0 1 2 3 4]
Minimum element from the above array is :  0


In [23]:
# getting mean of elements of the array
print("Our original array is : ",one_array)
print("Mean of elements of the above array is : ",one_array.mean())

Our original array is :  [0 1 2 3 4]
Mean of elements of the above array is :  2.0


In [24]:
# axis 0 is along columns
large_array=np.array([[0,1,2,3,4],[5,6,7,8,9],[10,11,12,13,14],[15,16,17,18,19]])
print("Our original array is : ")
print(large_array)
print("Sum of elements along axis 0")
print(large_array.sum(axis=0))

Our original array is : 
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
Sum of elements along axis 0
[30 34 38 42 46]


In [25]:
# axis 1 is along rows
large_array=np.array([[0,1,2,3,4],[5,6,7,8,9],[10,11,12,13,14],[15,16,17,18,19]])
print("Our original array is : ")
print(large_array)
print("Sum of elements along axis 1")
print(large_array.sum(axis=1))

Our original array is : 
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
Sum of elements along axis 1
[10 35 60 85]


In [26]:
large_array=np.array([[0,1,2,3,4],[5,6,7,8,9],[10,11,12,13,14],[15,16,17,18,19]])
print("Our original array is : ")
print(large_array)
print("Cumulative sum of above array, along axis 1 is : ")
print(large_array.cumsum(axis=1))

Our original array is : 
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
Cumulative sum of above array, along axis 1 is : 
[[ 0  1  3  6 10]
 [ 5 11 18 26 35]
 [10 21 33 46 60]
 [15 31 48 66 85]]


In [27]:
large_array=np.array([[0,1,2,3,4],[5,6,7,8,9],[10,11,12,13,14],[15,16,17,18,19]])
print("Our original array is : ")
print(large_array)
print("Cumulative sum of above array,along axis 0 is : ")
print(large_array.cumsum(axis=0))

Our original array is : 
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
Cumulative sum of above array,along axis 0 is : 
[[ 0  1  2  3  4]
 [ 5  7  9 11 13]
 [15 18 21 24 27]
 [30 34 38 42 46]]


In [28]:
# taking two new arrays
new_array_one=np.array([[1,1],[0,1]])
new_array_two=np.array([[2,0],[3,4]])
print("Our original array_one is : ")
print(new_array_one)
print("Our original array_two is : ")
print(new_array_two)

Our original array_one is : 
[[1 1]
 [0 1]]
Our original array_two is : 
[[2 0]
 [3 4]]


In [29]:
#element wise multiplication
print("Our original array_one is : ")
print(new_array_one)
print("Our original array_two is : ")
print(new_array_two)
print("Element wise multiplication of above two arrays : ")
print(new_array_one*new_array_two)

Our original array_one is : 
[[1 1]
 [0 1]]
Our original array_two is : 
[[2 0]
 [3 4]]
Element wise multiplication of above two arrays : 
[[2 0]
 [0 4]]


In [30]:
new_array_one=np.array([[1,1],[0,1]])
new_array_two=np.array([[2,0],[3,4]])
print("Our original array_one is : ")
print(new_array_one)
print("Our original array_two is : ")
print(new_array_two)
#matrix multiplication
print("Matrix multiplication of above two arrays : ")
print(new_array_one@new_array_two)

Our original array_one is : 
[[1 1]
 [0 1]]
Our original array_two is : 
[[2 0]
 [3 4]]
Matrix multiplication of above two arrays : 
[[5 4]
 [3 4]]


In [31]:
new_array_one=np.array([[1,1],[0,1]])
new_array_two=np.array([[2,0],[3,4]])
print("Our original array_one is : ")
print(new_array_one)
print("Our original array_two is : ")
print(new_array_two)
#matrix multiplication
print("Matrix multiplication of above two arrays : ")
print(new_array_one.dot(new_array_two))

Our original array_one is : 
[[1 1]
 [0 1]]
Our original array_two is : 
[[2 0]
 [3 4]]
Matrix multiplication of above two arrays : 
[[5 4]
 [3 4]]


In [32]:
# creating new array using arange function
new_array=np.arange(10)
print("Our new array is : ",new_array)

Our new array is :  [0 1 2 3 4 5 6 7 8 9]


In [33]:
# slicing on array elements
print("Our new array is : ",new_array)
print("After slicing applied on array elemnts : ")
print("new_array[2:5] : ",new_array[2:5])

Our new array is :  [0 1 2 3 4 5 6 7 8 9]
After slicing applied on array elemnts : 
new_array[2:5] :  [2 3 4]


In [34]:
# we can access individual element using index
print("Our new array is : ",new_array)
print("We want 5th element from above array : ")
print("new_array[5] ", new_array[5])

Our new array is :  [0 1 2 3 4 5 6 7 8 9]
We want 5th element from above array : 
new_array[5]  5


In [35]:
print("Our original array is : ",new_array)
# every second element will get assigned to 1000
new_array[::2]=1000
print("Every second element of above array will get assigned with 1000")
print("After modification array is : ",new_array)

Our original array is :  [0 1 2 3 4 5 6 7 8 9]
Every second element of above array will get assigned with 1000
After modification array is :  [1000    1 1000    3 1000    5 1000    7 1000    9]


In [36]:
print("Our original array is : ",new_array)
print("Every second element of above array will get assigned with 2000,upto 7th element")
new_array[:7:2]=2000
print("After modification array is : ",new_array)

Our original array is :  [1000    1 1000    3 1000    5 1000    7 1000    9]
Every second element of above array will get assigned with 2000,upto 7th element
After modification array is :  [2000    1 2000    3 2000    5 2000    7 1000    9]


In [37]:
# creating new array
new_array=np.arange(15).reshape(3,5)
print("Our created new array is : ")
print(new_array)

Our created new array is : 
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [38]:
print("Our created new array is : ")
print(new_array)
print("Getting 0th rows element upto index 3")
print("new_array[0][:4] : ",new_array[0][:4])

Our created new array is : 
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
Getting 0th rows element upto index 3
new_array[0][:4] :  [0 1 2 3]


In [39]:
print("Our created new array is : ")
print(new_array)
# we can apply slicing on rows and columns seperately 
print("After slicing on rows and columns")
print("new_array[0:2,1:3] :  ")
print(new_array[0:2,1:3])

Our created new array is : 
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
After slicing on rows and columns
new_array[0:2,1:3] :  
[[1 2]
 [6 7]]


In [40]:
# taking transpose of a matrix
print("Our original matrix is : ")
print(new_array)
print("Transpose of above matrix is : ")
print(new_array.T)

Our original matrix is : 
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
Transpose of above matrix is : 
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


In [41]:
# flattening array into 1-D array
array_iterator=new_array.flat
print("It returns iterator object : ",array_iterator)
print("Our original array is : ")
print(new_array)
print("Our flattened array is : ")
for element in array_iterator:
    print(element,end=" ")

It returns iterator object :  <numpy.flatiter object at 0x0000000000558840>
Our original array is : 
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
Our flattened array is : 
0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 

In [42]:
# flattening array into 1-D array
print("Our original array is : ")
print(new_array)
print("Our flattened array is : ")
print(new_array.ravel())

Our original array is : 
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
Our flattened array is : 
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [43]:
new_array_one=np.array([[1,1],[0,1]])
new_array_two=np.array([[2,0],[3,4]])


In [44]:
print("Our original array one is : ")
print(new_array_one)
print("Our original array two is : ")
print(new_array_two)
# vstack , vertically stacks the elements of array
# and returns new array
print("After applying vstack on above two arrays : ")
print(np.vstack((new_array_one,new_array_two)))

Our original array one is : 
[[1 1]
 [0 1]]
Our original array two is : 
[[2 0]
 [3 4]]
After applying vstack on above two arrays : 
[[1 1]
 [0 1]
 [2 0]
 [3 4]]


In [45]:
print("Our original array one is : ")
print(new_array_one)
print("Our original array two is : ")
print(new_array_two)
# hstack , horizontally stacks the elements of array
# and returns new array
print("After applying hstack on above two arrays : ")
print(np.hstack((new_array_one,new_array_two)))

Our original array one is : 
[[1 1]
 [0 1]]
Our original array two is : 
[[2 0]
 [3 4]]
After applying hstack on above two arrays : 
[[1 1 2 0]
 [0 1 3 4]]


In [46]:
original_array=np.arange(12).reshape(3,4)
print("Our original array is : ")
print(original_array)

Our original array is : 
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [47]:
# array.view(), makes copy of the orginal array
# with different memory location
copied_array=original_array.view()
copied_array=copied_array.reshape(12,1)
print("ID of original array is : ",id(original_array))
print("ID of copied array is : ",id(copied_array))

ID of original array is :  293630720
ID of copied array is :  84496096


In [48]:
# making changes in copied array
copied_array[2]=1000

In [49]:
# changes in copied array got reflected in original array
original_array

array([[   0,    1, 1000,    3],
       [   4,    5,    6,    7],
       [   8,    9,   10,   11]])

In [50]:
copied_array

array([[   0],
       [   1],
       [1000],
       [   3],
       [   4],
       [   5],
       [   6],
       [   7],
       [   8],
       [   9],
       [  10],
       [  11]])

In [51]:
print(original_array)

[[   0    1 1000    3]
 [   4    5    6    7]
 [   8    9   10   11]]
