
#### Q1. How to import numpy as np and see the version?

In [1]:
import numpy as np
print(np.__version__)

1.18.1


#### Q2.How to create a 1D array?

In [2]:
number_array = np.arange(10)
number_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### Q3.How to create a 3×3 numpy array of all True’s?

In [3]:
boolean_array=np.full((3, 3), True, dtype=bool)
boolean_array

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

#### Q4.How to extract all odd numbers from array? 

In [5]:
number_array = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
# Solution
print("Our original number_array is : ")
print(number_array)
print("Odd elements in number_array are : ")
print(number_array[number_array % 2 == 1])

Our original number_array is : 
[0 1 2 3 4 5 6 7 8 9]
Odd elements in number_array are : 
[1 3 5 7 9]


#### Q5.How replace all odd numbers in array with -1?

In [7]:
number_array = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print("Our original array is : ")
print(number_array)
print("After replacing odd numbers with -1 : ")
number_array[number_array % 2 == 1] = -1
print(number_array)

Our original array is : 
[0 1 2 3 4 5 6 7 8 9]
After replacing odd numbers with -1 : 
[ 0 -1  2 -1  4 -1  6 -1  8 -1]


#### Q6.How to replace all odd numbers in array with -1 without changing array?

In [9]:
number_array = np.arange(10)
output_array = np.where(number_array % 2 == 1, -1, number_array)
print("Our orginal array remains as it is: ")
print(number_array)
print("Modified array is: ")
print(output_array)

Our orginal array remains as it is: 
[0 1 2 3 4 5 6 7 8 9]
Modified array is: 
[ 0 -1  2 -1  4 -1  6 -1  8 -1]


#### Q7. How to convert a 1D array to a 2D array with 2 rows?


In [16]:
data_array = np.arange(10)
data_array.reshape(2, -1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [17]:
data_array = np.arange(10)
data_array.reshape(5, -1)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

#### Q8.How to stack two arrays vertically?

In [20]:
array_one = np.arange(10).reshape(2,-1)
array_two = np.repeat(1, 10).reshape(2,-1)
print("Our array_one is : ")
print(array_one)
print("Our array_two is : ")
print(array_two)

Our array_one is : 
[[0 1 2 3 4]
 [5 6 7 8 9]]
Our array_two is : 
[[1 1 1 1 1]
 [1 1 1 1 1]]


In [21]:
# method 1:
np.concatenate([array_one, array_two], axis=0)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [22]:
# method 2:
np.vstack([array_one, array_two])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [23]:
# method 3:
np.r_[array_one, array_two]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

#### Q9.How to stack two arrays horizontally?

In [24]:
array_one = np.arange(10).reshape(2,-1)
array_two = np.repeat(1, 10).reshape(2,-1)
print("Our array_one is : ")
print(array_one)
print("Our array_two is : ")
print(array_two)

Our array_one is : 
[[0 1 2 3 4]
 [5 6 7 8 9]]
Our array_two is : 
[[1 1 1 1 1]
 [1 1 1 1 1]]


In [25]:
# method 1:
np.concatenate([array_one, array_two], axis=1)

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [26]:
# method 2:
np.hstack([array_one, array_two])

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [27]:
# method 3:
np.c_[array_one, array_two]

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

#### Q10. How to create the following pattern without hardcoding. Use only numpy functions and the below input array, data_array?

###### Input:

###### data_array = np.array([1,2,3])`

###### Output:

###### array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [28]:
data_array = np.array([1,2,3])
np.r_[np.repeat(data_array, 3), np.tile(data_array, 3)]

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

#### Q11.How to get the common items between two arrays?

###### Input:

###### array_one = np.array([1,2,3,2,3,4,3,4,5,6]) array_two = np.array([7,2,10,2,7,4,9,4,9,8])

###### Desired Output:

###### array([2, 4])

In [30]:
array_one=np.array([1,2,3,2,3,4,3,4,5,6])
array_two=np.array([7,2,10,2,7,4,9,4,9,8])
print("Our array_one is : ",array_one)
print("Our array_two is : ",array_two)

Our array_one is :  [1 2 3 2 3 4 3 4 5 6]
Our array_two is :  [ 7  2 10  2  7  4  9  4  9  8]


In [31]:
np.intersect1d(array_one,array_two)

array([2, 4])

#### Q12. How to remove elements from array_a present in array_b ?
##### array_one = np.array([1,2,3,4,5]) array_two = np.array([5,6,7,8,9])

##### Desired Output:

###### array([1,2,3,4])

In [32]:
array_a = np.array([1,2,3,4,5])
array_b = np.array([5,6,7,8,9])

# from 'array_a' remove all of 'array_b'
np.setdiff1d(array_a,array_b)

array([1, 2, 3, 4])


#### Q13.How to get the positions where elements of array_a and array_b match ?

##### array_a = np.array([1,2,3,2,3,4,3,4,5,6]) array_b = np.array([7,2,10,2,7,4,9,4,9,8])

###### Desired Output:

###### (array([1, 3, 5, 7]),)

In [34]:
array_a = np.array([1,2,3,2,3,4,3,4,5,6])
array_b = np.array([7,2,10,2,7,4,9,4,9,8])

np.where(array_a == array_b)

(array([1, 3, 5, 7], dtype=int64),)

#### Q14. How to get all items between 5 and 10 from array_a?

##### Input:

###### array_a = np.array([2, 6, 1, 9, 10, 3, 27])

##### Desired Output:

##### (array([6, 9, 10]),)

In [35]:
array_a=np.array([2,6,1,9,10,3,27])
# method 1
index = np.where((array_a >= 5) & (array_a <= 10))
array_a[index]

array([ 6,  9, 10])

In [36]:
# method 2
index = np.where(np.logical_and(array_a>=5, array_a<=10))
array_a[index]

array([ 6,  9, 10])

In [38]:
# method 3: 
array_a[(array_a >= 5) & (array_a <= 10)]

array([ 6,  9, 10])

#### Q15. How to reverse the rows of a 2D array array_one?

###### Input

##### array_one = np.arange(9).reshape(3,3)

In [45]:
array_one = np.arange(9).reshape(3,3)
print("Our original 2D array is : ")
print(array_one)
# it does not change original array
print("After reversing rows of array_one is : ")
print(array_one[::-1])

Our original 2D array is : 
[[0 1 2]
 [3 4 5]
 [6 7 8]]
After reversing rows of array_one is : 
[[6 7 8]
 [3 4 5]
 [0 1 2]]


#### Q16. How to reverse the columns of a 2D array array_one?

###### Input

##### array_one = np.arange(9).reshape(3,3)

In [46]:
array_one = np.arange(9).reshape(3,3)
print("Our original array is : ")
print(array_one)
print("After reversing columns of array_one is : ")
print(array_one[:, ::-1])

Our original array is : 
[[0 1 2]
 [3 4 5]
 [6 7 8]]
After reversing columns of array_one is : 
[[2 1 0]
 [5 4 3]
 [8 7 6]]



#### Q17. How to create a 2D array of shape 5x3 to contain random decimal numbers between 5 and 10?

In [49]:
print("Using first method")
print()
# method 1:
random_numbers_array = np.random.randint(low=5, high=10, size=(5,3)) + np.random.random((5,3))
print(random_numbers_array)
print()
print("Using second method")
print()
# method 2:
random_numbers_array = np.random.uniform(5,10, size=(5,3))
print(random_numbers_array)

Using first method

[[6.78220897 8.77279814 7.8717555 ]
 [6.50891296 8.95136305 6.71340842]
 [9.5441114  5.72721359 5.64707896]
 [8.13573784 8.03566809 5.25412567]
 [7.42542271 6.50820814 5.82700672]]

Using second method

[[6.87234847 9.6241871  8.78542456]
 [7.21642407 6.00795103 5.99313439]
 [6.80236183 9.5912383  9.75544283]
 [7.06111193 9.16851594 5.00269991]
 [5.54145793 6.16442153 9.82865879]]
